language: elixir
elixir:
  - 1.2.2
  - 1.3.0
sudo: false # to use faster container based build environment
otp_release:
  - 18.2.1
after_script:
  - mix credo -a
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
